name: Nodejs-AWS-CICD

on:
  push:
    branches: [ master ]

stages:
  - Build
  - Test
  - Deploy

jobs:
  build:
    stage: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build

  test:
    stage: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: yarn test

  deploy:
    stage: Deploy
    runs-on: ubuntu-latest
    needs: test
    environment: production
    steps:
      - uses: actions/checkout@v2
      - run: echo "Deploying to AWS"