stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:16-slim
  script:
    - npm install
    - npm run build

test:
  stage: test
  image: node:16-slim
  script:
    - npm test

deploy:
  stage: deploy
  image: node:16-slim
  script:
    - aws deploy pushr --application-name my-node-app --s3-bucket my-s3-bucket --source 