stages:
  - build
  - test
  - docker-build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build

test:
  stage: test
  script:
    - npm test

docker-build:
  stage: docker-buildweqfdwef
  image: docker:latest
  script:
    - docker build -t my-app:latest .

deploy:
  stage: deploy
  image: aws/codedeploy:latest
  script:
    - aws deploy create-deployment --application-name my-app --deployment-group-name my-test-group --deployment-config-name my-test-config --s3-location bucket=my-bucket,key=my-app.zip,bundle-type=zip --file-exists-behavior OVERWRITE