```
pipeline {
  agent any

  stages {
    stage('Clone') {
      steps {
        git 'https://github.com/GoogleCloudPlatform/python-docs-samples'
      }
    }

    stage('Build') {
      steps {
        sh 'python setup.py sdist'
      }
    }

    stage('Test') {
      steps {
        sh 'python -m pytest -v test/test_main.py'
      }
    }

    stage('Deploy') {
      steps {
        genai() {
          copy('sdist/sample-project-*.tar.gz', 'gs://my-bucket/artifacts/')
        }
      }
    }
  }
}
```