pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn package'
            }
        }

        stage('Package') {
            steps {
                sh 'mvn jar:jar'
            }
        }

        stage('Create Docker Image') {
            steps {
                docker.build image: 'my-image', dockerfile: 'Dockerfile'
            }
        }

        stage('Scan Docker Image') {
            steps {
                docker.scan image: 'my-image'
            }
        }

        stage('Publish Docker Image') {
            steps {
                docker.push image: 'my-image'
            }
        }

        stage('Scan for Secrets') {
            steps {
                sh 'secret-scanner scan'
            }
        }
    }
}